### ISSUE TITLE
Error handling does not work properly

### ISSUE THREAD

**Issue by Blucbo** [GoogleChromeLabs/serial-terminal#5] opened 2019-10-16 15:35 UTC
Hi, thank you, that's a very good project(serial-terminal).
I use this demo and have a problem. Debugging found one error with calling `getReader`.
```
while (port.readable) {
    try {
        reader = port.readable.getReader(); <-- repeat call getReader with error
        while (true) {
            const {value, done} = await reader.read();
            term.writeUtf8(value);
            if (done) {
                break;
            }
        }
        reader = undefined;
    } catch (e) {
        term.writeln(`<ERROR: ${e.message}>`);
    }
}
```
In this case throw error break loop and we again call `getReader` and have exception like `'Failed to execute 'getReader' on 'ReadableStream': ReadableStreamReader constructor can only accept readable streams that are not yet locked to a reader'`
So I suggest move  `reader = port.readable.getReader();` above loop or check reader is exist.
Like this:
```
// start above reader
reader = port.readable.getReader();
// end above reader
while (port.readable) {
    try {
        while (true) {
            const {value, done} = await reader.read();
            term.writeUtf8(value);
            if (done) {
                break;
            }
        }
    } catch (e) {
        term.writeln(`<ERROR: ${e.message}>`);
    }
}
```
or 
```
while (port.readable) {
    try {
       // start add check
       if (!reader) {
            reader = port.readable.getReader();
        } 
       // end add check
        while (true) {
            const {value, done} = await reader.read();
            term.writeUtf8(value);
            if (done) {
                break;
            }
        }
        reader = undefined;
    } catch (e) {
        term.writeln(`<ERROR: ${e.message}>`);
    }
}
```

**Comment by reillyeon** [comment] 2019-10-16 17:35
Thank you for reporting this issue. Can you give me more information so I can reproduce this behavior myself? What version of Chrome are you using? What kind of error is being encountered that causes the stream to close?

When `read()` returns with `done` equal to `true` `port.readable` should be initialized with a new stream that is unlocked so that the next iteration of the outer loop can create a new reader and continue reading. This is the behavior I observe in my testing.

**Comment by Blucbo** [comment] 2019-10-17 14:13
Windows pro 10
Chrome 79.0.3944.0 (Development) canary (64-bit) with enabled chrome://flags/#enable-experimental-web-platform-features

```
while (port.readable) {
    try {
        reader = port.readable.getReader(); 
        while (true) {
            const {value, done} = await reader.read();
            term.writeUtf8(value);
            throw new TypeError('This error broke code :('); <-- paste this for reproduce
            if (done) {
                break;
            }
        }
        reader = undefined;
    } catch (e) {
        term.writeln(`<ERROR: ${e.message}>`);
    }
}
```
Сall once `throw error` creates infinite loop with error `getReader()`
![loopError](https://user-images.githubusercontent.com/17926137/67016559-0c971500-f101-11e9-857e-2352631ff76d.png)

**Comment by reillyeon** [comment] 2019-10-17 17:38
Am I understanding correctly from your example that the error triggering the problem is not thrown by `reader.read()` but by an error in code you've added to the inner loop?

In that case it is expected that the code would need to change because the current try/catch block correctly assumes that `reader.read()` is the only line that will throw an error. If you've added new code to this loop perhaps it should be enclosed in its own try/catch block.

**Comment by Blucbo** [comment] 2019-10-18 06:38
Yes, error is not `reader.read()`.
I think quantity try/catch in  try/catch make difficult reading code than by condition like this:
```
while (port.readable) {
    try {
       // start add check
       if (!reader) {
            reader = port.readable.getReader();
        } 
       // end add check
        while (true) {
            const {value, done} = await reader.read();
            term.writeUtf8(value);
            if (done) {
                break;
            }
        }
        reader = undefined;
    } catch (e) {
        term.writeln(`<ERROR: ${e.message}>`);
    }
}
```

**Comment by reillyeon** [comment] 2019-10-18 18:23
Closing this issue. The suggested changes are not necessary for the code as written. Developers modifying this code should consider the needs of their particular application.

**Closed by reillyeon** 2019-10-18 18:23 UTC
